name: CD - Prod Deployment (Branch)

on:
  push:
    branches: [ prod ]

env:
  DATABRICKS_HOST: https://adb-1108654228307752.12.azuredatabricks.net

jobs:
  deploy-prod:
    name: Deploy to Prod
    runs-on: ubuntu-latest

    env:
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Databricks CLI
        run: |
          pip install --upgrade pip
          pip install 'databricks-cli>=0.220.0'

      - name: Validate bundle
        run: databricks bundle validate -t prod

      - name: Deploy to Prod
        run: databricks bundle deploy -t prod --var="git_sha=${{ github.sha }}"
